### PR TITLE
Extensibility points

### PR DESCRIPTION
**Pull request by dquintela**
In our project we already have a custom spring data repository, so we cannot use the proposed integration directly. We need to create a composite JpaRepositoryFactoryBean to merge our custom repository with spring-data-envers's one, and some little extension points were needed.

This was made against branch 1.1.x.

Best regards
Diogo

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dquintela Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=82)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=82) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dquintela Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=82)!

**Comment by schauder** [comment]
I can understand why you want the Factory to be public. 

But what is the intent behind in making `DefaultRevisionEntityInformation` public? 
Same question for `protected Class<?> revisionEntityClass;`

**Comment by schauder** [comment]
Closing for lack of feedback.

**Pull request closed without merging**
