### PR TITLE
fixes spring-projects/spring-data-envers#9 - added ability to sort re…

### PR DESCRIPTION
**Pull request by matthewdfleming**
Crap the spacing is off.. mainly the mod is in the impl class to `findRevisions(ID id, Pageable pageable)`.

### CODE REVIEW

**Comment by olivergierke** [comment]
This not going to work really with all the unrelated changes. Also, as indicated in the ticket you're attempting to fix, what problem are we solving in the first place? `Pageable`s provide a `Sort` instance already. Would you mind sharing your thoughts on the ticket to clarify the why before discuss implementations?

**Comment by matthewdfleming** [comment]
Right. I'm just now making use of the Sort inside the Pageable. So the requirement I was implementing was to add the ability to sort the revision list for an entity. The current sort (without this change) is by revision number ascending. Let's say you wanted to sort by revision number descending (this is what I changed the test to use), you can add a sort on the 'revisionNumber' property. Let's say that you had a custom revision entity that had a pointer to a User object and on the User object you had a field called name... you can now sort by 'revisionProperty.user.name' and the revisions will come back in that order.

**Comment by madness-inc** [comment]
See also #55  -> [DATACMNS-888](https://jira.spring.io/browse/DATACMNS-888) which is fixed in 1.13 RC1

**Comment by madness-inc** [comment]
Just as a suggestion, it would also be possible to support sorting by **any number** of attributes.
A possible implementation would look like:
`public Page<Revision<N, T>> findRevisions(ID id, Pageable pageable) {
	Class<T> type = entityInformation.getJavaType();
	AuditReader reader = AuditReaderFactory.get(entityManager);
	List<Number> allRevisionNumbers = reader.getRevisions(type, id);
	if (pageable.getOffset() > allRevisionNumbers.size()) {
		return new PageImpl<Revision<N, T>>(Collections.<Revision<N, T>> emptyList(), pageable, 0);
	}
	AuditQuery query = reader.createQuery().forRevisionsOfEntity(type, type.getName(), false, true);
	query.addProjection(AuditEntity.revisionNumber());
	query.add(AuditEntity.id().eq(id));
	query.setFirstResult(pageable.getOffset());
	query.setMaxResults(pageable.getPageSize());
	if (null == pageable.getSort()) {
		query.addOrder(AuditEntity.revisionNumber().asc());
	} else {
		for (Sort.Order order : pageable.getSort()) {
			AuditProperty<?> property = 
				"revisionNumber".equals(order.getProperty()) ? AuditEntity.id()
					: AuditEntity.property(order.getProperty());
			boolean asc = Direction.ASC.equals(order.getDirection());
			query.addOrder(asc ? property.asc() : property.desc());
		}
	}
	List<N> revisionNumbers = query.getResultList();
	List<Revision<N, T>> content = new ArrayList<Revision<N, T>>();
	for (N revisionNumber : revisionNumbers) {
		content.add(findRevision(id, revisionNumber));
	}
	return new PageImpl<Revision<N, T>>(content, pageable, allRevisionNumbers.size());
}`

**Comment by matthewdfleming** [comment]
So the DATACMNS-888 fixes sorting on the revision object only (I think). If you have a revision object that encapsulates a different entity and you wanted to sort by that entities' attributes, is what this pull request has. Now it's been so long that the there are merge conflicts. Do you understand the use case? Is it worth it for me to update the pull request?

**Comment by pivotal-issuemaster** [comment]
@matthewdfleming Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=42) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@matthewdfleming Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=42)!

**Comment by schauder** [comment]
The issue which this intended to fix was solved otherwise.

**Pull request closed without merging**
