### PR TITLE
Introduce EnableEnversRepositories meta-annotation

### LINKED ISSUE #289: Investigate `@EnableEnversRepositories` meta-annotation
A composed annotation meta-annotated with `@EnableJpaRepositories(repositoryFactoryBeanClass = EnversRevisionRepositoryFactoryBean.class)` would be nice to have.

### PR DESCRIPTION
**Pull request by mp911de**
We now provide a composed annotation to enable Envers repositories without the need to specify a custom repository base class.

Closes #289

### CODE REVIEW

**Comment by odrotbohm** [comment]
LGTM!

**Comment by scordio** [comment]
Hi @mp911de, would it be an option to also cover what is described in https://github.com/spring-projects/spring-data-envers/issues/4#issuecomment-8979094, i.e., customizing the revision entity class?

**Comment by mp911de** [comment]
Introducing envers-specific property values would require a whole lot more to make this work including an envers-specific `EnversRepositoryConfigExtension` subclassing `JpaRepositoryConfigExtension`. Config extensions were never meant to be public in the first place.

Right now we can get away with a composed annotation that overrides the repository bean factory class.

**Comment by schauder** [comment]
Thanks Mark. That's merged.

**Pull request closed without merging**
