### PR TITLE
added ability to searching deleted entities. Fixed #21.

### LINKED ISSUE #21: load revisions after deleted entity
simple sample : Entity A
- insert A , modify A
  findByRevision(...) returns 2 entries
- delete A
  findRevision raised an exception: because in the class org.springframework.data.history.Revision entity is null

how can i load all audited values of A.

### PR DESCRIPTION
**Pull request by nikpetrovic**
I have added flag for searching deleted entities so there is no more exception on querying entities that have RevisionType.DEL. This fixes also #13.

### CODE REVIEW

**Comment by george-y** [comment]
We've recently come across the same issue with deleted entities. It would be great if the pull request from @nikpetrovic could be merged with master.

**Comment by vinnieashken** [comment]
This fix is not available in version 0.3.0

**Comment by nikpetrovic** [comment]
Any update on this?

**Comment by Ungomma** [comment]
I second the request to merge this! The bug is real.

**Comment by kengurr** [comment]
+1

**Comment by kjartanrh** [comment]
+1

**Comment by Zeljko34** [comment]
Should be merged.

**Comment by mcnaggets** [comment]
+1

**Comment by htmsousa** [comment]
+1

**Comment by razorvind** [comment]
+1

**Comment by pivotal-issuemaster** [comment]
@nikpetrovic Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=27) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by ripper2hl** [comment]
Please fix this!

**Comment by ripper2hl** [comment]
@nikpetrovic it seems that disappeared from the earth , why not fork her patch and merge this fix , her profile not have any activity from august to date and i cant see any contact information

**Comment by pivotal-issuemaster** [comment]
@nikpetrovic Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=27)!

**Comment by itcaso** [comment]
Hey do the merge please!!...

**Comment by lJesusFloresl** [comment]
I have the same issue, please fix this!! Do the merge...

**Comment by jleemans** [comment]
Any reason why this is not merged yet? What's the status on this? Thx.

**Comment by Alwaysgone** [comment]
👍

**Comment by lkerck** [comment]
👍

**Comment by schauder** [comment]
That's merged. Thanks.

**Pull request closed without merging**
