### PR TITLE
Added support for QueryDSL's QueryDslPredicateExecutor. Fixes #30

### LINKED ISSUE #30: Spring-data-envers incompatible with QueryDSL
I'm creating a github ticket for this old issue as I don't think it has been resolved. https://jira.spring.io/browse/DATAJPA-387 or
http://forum.springsource.org/showthread.php?129116-Repository-extending-spring-data-envers-and-querydsl

### PR DESCRIPTION
**Pull request by jihlee**
Rebased @dmytr 's querydsl branch to current master in PR #37

### CODE REVIEW

**Comment by fischey** [comment]
+1 from me. Works like a charm on the current branch.

**Comment by igler** [comment]
Would be cool to see this in 1.0.3.RELEASE.

**Comment by pivotal-issuemaster** [comment]
@jihlee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=45) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jihlee Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-envers&pullRequestId=45)!

**Comment by schauder** [comment]
Replaced by #109.

**Pull request closed without merging**
